"""
Report generation for routing algorithm study.

Generates a summary markdown report with:
- Key findings
- Hypothesis validation
- Recommendations
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd
import numpy as np


# Default output directory
DEFAULT_OUTPUT_DIR = Path("/tmp/routing_results")


REPORT_TEMPLATE = """# Ray Serve Routing Algorithm Study - Results Report

**Generated:** {timestamp}

**Total Experiments:** {total_runs}
**Configurations Tested:** {unique_configs}

---

## Executive Summary

{executive_summary}

---

## Key Findings

### 1. Latency Performance

{latency_findings}

![Latency by Scale]({figures_dir}/latency_by_scale.png)

![Latency Breakdown]({figures_dir}/latency_breakdown.png)

### 2. Fairness Analysis

{fairness_findings}

![Fairness Comparison]({figures_dir}/fairness_comparison.png)

![Replica Coverage]({figures_dir}/replica_coverage.png)

### 3. Throughput Analysis

{throughput_findings}

![Throughput vs Latency]({figures_dir}/throughput_vs_latency.png)

![Error Rate by Load]({figures_dir}/error_rate_by_load.png)

### 4. Utilization Analysis

{utilization_findings}

![Utilization Comparison]({figures_dir}/utilization_comparison.png)

---

## Routing Delay Analysis

### Client → Parent Delay

This measures time from when the client sends a request to when the parent replica receives it.
High values indicate router bottleneck (e.g., queue length probing blocking the request path).

![Client to Parent Delay]({figures_dir}/client_to_parent_delay.png)

### Parent → Child Delay

This measures time from when the parent sends to child to when the child receives it.
Includes routing decision time + network RTT + queue wait.

![Parent→Child Delay Comparison]({figures_dir}/parent_child_delay_comparison.png)

---

## Hypothesis Validation

### Hypothesis 1: Pow2 Improves Tail Latency
**Expectation:** Pow2 will show lower p99 latency than Random/RoundRobin.

{hypothesis_1}

### Hypothesis 2: Pow2 Improves Fairness
**Expectation:** Pow2 will show higher Jain's Index than Random.

{hypothesis_2}

### Hypothesis 3: RoundRobin Has Best Fairness
**Expectation:** RoundRobin will show near-perfect fairness (Jain's ≈ 1.0).

{hypothesis_3}

---

## Detailed Results by Algorithm

{algorithm_tables}

---

## Configuration Impact Analysis

### Scale Impact
{scale_impact}

![Heatmap: Latency by Algorithm and Scale]({figures_dir}/heatmap_latency_p99_algo_scale.png)

### Topology Impact (Large Scale)
{topology_impact}

### Locality Impact (Large Scale)
{locality_impact}

![Algorithm Heatmap (Large Scale)]({figures_dir}/algorithm_heatmap_large.png)

---

## Recommendations

{recommendations}

---

## Appendix: Data Summary

### Latency Percentiles by Algorithm (mean across all runs)

{latency_table}

### Client → Parent Delay by Algorithm

{client_to_parent_table}

### Parent → Child Delay by Algorithm

{parent_to_child_table}

### Simulated Latency by Algorithm (Actual Work Time)

{simulated_latency_table}

### Fairness Metrics by Algorithm (mean across all runs)

{fairness_table}

### Utilization Metrics by Algorithm

{utilization_table}

---

*Report generated by routing algorithm study analysis pipeline.*
"""


def compute_algorithm_summary(df: pd.DataFrame, algorithm: str) -> Dict:
    """Compute summary statistics for an algorithm."""
    alg_df = df[df["algorithm"] == algorithm]

    return {
        "algorithm": algorithm,
        "runs": len(alg_df),
        "latency_p50_mean": alg_df["latency_p50"].mean(),
        "latency_p99_mean": alg_df["latency_p99"].mean(),
        "latency_p99_std": alg_df["latency_p99"].std(),
        "child_jains_mean": alg_df["child_jains"].mean(),
        "child_jains_std": alg_df["child_jains"].std(),
        "goodput_mean": alg_df["goodput"].mean(),
        "error_rate_mean": alg_df["error_rate"].mean(),
    }


def format_latency_table(df: pd.DataFrame) -> str:
    """Format latency statistics as markdown table."""
    rows = []
    rows.append("| Algorithm | p50 (ms) | p90 (ms) | p95 (ms) | p99 (ms) | Max (ms) |")
    rows.append("|-----------|----------|----------|----------|----------|----------|")

    for alg in df["algorithm"].unique():
        alg_df = df[df["algorithm"] == alg]
        rows.append(
            f"| {alg.replace('_', ' ').title()} | "
            f"{alg_df['latency_p50'].mean():.1f} | "
            f"{alg_df['latency_p90'].mean():.1f} | "
            f"{alg_df['latency_p95'].mean():.1f} | "
            f"{alg_df['latency_p99'].mean():.1f} | "
            f"{alg_df['latency_max'].mean():.1f} |"
        )

    return "\n".join(rows)


def format_parent_to_child_table(df: pd.DataFrame) -> str:
    """Format parent-to-child delay statistics as markdown table."""
    if "parent_child_delay_mean" not in df.columns:
        return "*Parent→Child delay data not available.*"
    
    rows = []
    rows.append("| Algorithm | Mean (ms) | p50 (ms) | p90 (ms) | p99 (ms) |")
    rows.append("|-----------|-----------|----------|----------|----------|")

    for alg in df["algorithm"].unique():
        alg_df = df[df["algorithm"] == alg]
        rows.append(
            f"| {alg.replace('_', ' ').title()} | "
            f"{alg_df['parent_child_delay_mean'].mean():.2f} | "
            f"{alg_df['parent_child_delay_p50'].mean():.2f} | "
            f"{alg_df['parent_child_delay_p90'].mean():.2f} | "
            f"{alg_df['parent_child_delay_p99'].mean():.2f} |"
        )

    return "\n".join(rows)


def format_simulated_latency_table(df: pd.DataFrame) -> str:
    """Format simulated latency (actual work time) statistics as markdown table."""
    rows = []
    rows.append("| Algorithm | Mean (ms) | p50 (ms) | p90 (ms) | p99 (ms) |")
    rows.append("|-----------|-----------|----------|----------|----------|")

    for alg in df["algorithm"].unique():
        alg_df = df[df["algorithm"] == alg]
        rows.append(
            f"| {alg.replace('_', ' ').title()} | "
            f"{alg_df['simulated_latency_mean'].mean():.2f} | "
            f"{alg_df['simulated_latency_p50'].mean():.2f} | "
            f"{alg_df['simulated_latency_p90'].mean():.2f} | "
            f"{alg_df['simulated_latency_p99'].mean():.2f} |"
        )

    return "\n".join(rows)


def format_fairness_table(df: pd.DataFrame) -> str:
    """Format fairness statistics as markdown table."""
    rows = []
    
    # Check if unique_pct columns exist
    has_unique_pct = "child_unique_pct" in df.columns
    
    if has_unique_pct:
        rows.append("| Algorithm | Child Jain's | Child CV | Child Coverage % | Parent Jain's | Parent CV | Parent Coverage % |")
        rows.append("|-----------|--------------|----------|------------------|---------------|-----------|-------------------|")
    else:
        rows.append("| Algorithm | Child Jain's | Child CV | Parent Jain's | Parent CV |")
        rows.append("|-----------|--------------|----------|---------------|-----------|")

    for alg in df["algorithm"].unique():
        alg_df = df[df["algorithm"] == alg]
        if has_unique_pct:
            rows.append(
                f"| {alg.replace('_', ' ').title()} | "
                f"{alg_df['child_jains'].mean():.4f} | "
                f"{alg_df['child_cv'].mean():.4f} | "
                f"{alg_df['child_unique_pct'].mean():.1f}% | "
                f"{alg_df['parent_jains'].mean():.4f} | "
                f"{alg_df['parent_cv'].mean():.4f} | "
                f"{alg_df['parent_unique_pct'].mean():.1f}% |"
            )
        else:
            rows.append(
                f"| {alg.replace('_', ' ').title()} | "
                f"{alg_df['child_jains'].mean():.4f} | "
                f"{alg_df['child_cv'].mean():.4f} | "
                f"{alg_df['parent_jains'].mean():.4f} | "
                f"{alg_df['parent_cv'].mean():.4f} |"
            )

    return "\n".join(rows)


def format_client_to_parent_table(df: pd.DataFrame) -> str:
    """Format client-to-parent delay statistics as markdown table."""
    if "client_parent_delay_mean" not in df.columns:
        return "*Client→Parent delay data not available.*"
    
    rows = []
    rows.append("| Algorithm | Mean (ms) | p50 (ms) | p90 (ms) | p99 (ms) |")
    rows.append("|-----------|-----------|----------|----------|----------|")

    for alg in df["algorithm"].unique():
        alg_df = df[df["algorithm"] == alg]
        rows.append(
            f"| {alg.replace('_', ' ').title()} | "
            f"{alg_df['client_parent_delay_mean'].mean():.2f} | "
            f"{alg_df['client_parent_delay_p50'].mean():.2f} | "
            f"{alg_df['client_parent_delay_p90'].mean():.2f} | "
            f"{alg_df['client_parent_delay_p99'].mean():.2f} |"
        )

    return "\n".join(rows)


def format_utilization_table(df: pd.DataFrame) -> str:
    """Format utilization statistics as markdown table."""
    if "child_util_mean" not in df.columns:
        return "*Utilization data not available.*"
    
    rows = []
    rows.append("| Algorithm | Mean Util | Min Util | Max Util |")
    rows.append("|-----------|-----------|----------|----------|")

    for alg in df["algorithm"].unique():
        alg_df = df[df["algorithm"] == alg]
        rows.append(
            f"| {alg.replace('_', ' ').title()} | "
            f"{alg_df['child_util_mean'].mean():.2%} | "
            f"{alg_df['child_util_min'].mean():.2%} | "
            f"{alg_df['child_util_max'].mean():.2%} |"
        )

    return "\n".join(rows)


def validate_hypothesis_1(df: pd.DataFrame) -> str:
    """Validate Hypothesis 1: Pow2 improves tail latency."""
    pow2_p99 = df[df["algorithm"] == "pow2"]["latency_p99"].mean()
    random_p99 = df[df["algorithm"] == "random"]["latency_p99"].mean()
    rr_p99 = df[df["algorithm"] == "round_robin"]["latency_p99"].mean()

    pow2_vs_random = ((random_p99 - pow2_p99) / random_p99) * 100 if random_p99 > 0 else 0
    pow2_vs_rr = ((rr_p99 - pow2_p99) / rr_p99) * 100 if rr_p99 > 0 else 0

    if pow2_p99 < random_p99 and pow2_p99 < rr_p99:
        result = "**CONFIRMED** ✓"
        details = (
            f"Pow2 achieved {pow2_p99:.1f}ms p99 latency, which is "
            f"{pow2_vs_random:.1f}% lower than Random ({random_p99:.1f}ms) and "
            f"{pow2_vs_rr:.1f}% lower than Round-Robin ({rr_p99:.1f}ms)."
        )
    elif pow2_p99 < random_p99:
        result = "**PARTIALLY CONFIRMED**"
        details = (
            f"Pow2 ({pow2_p99:.1f}ms) outperformed Random ({random_p99:.1f}ms) "
            f"but not Round-Robin ({rr_p99:.1f}ms)."
        )
    else:
        result = "**NOT CONFIRMED** ✗"
        details = (
            f"Pow2 ({pow2_p99:.1f}ms) did not show lower p99 latency than "
            f"Random ({random_p99:.1f}ms) or Round-Robin ({rr_p99:.1f}ms)."
        )

    return f"**Result:** {result}\n\n{details}"


def validate_hypothesis_2(df: pd.DataFrame) -> str:
    """Validate Hypothesis 2: Pow2 improves fairness over Random."""
    pow2_jains = df[df["algorithm"] == "pow2"]["child_jains"].mean()
    random_jains = df[df["algorithm"] == "random"]["child_jains"].mean()

    improvement = ((pow2_jains - random_jains) / random_jains) * 100 if random_jains > 0 else 0

    if pow2_jains > random_jains:
        result = "**CONFIRMED** ✓"
        details = (
            f"Pow2 achieved Jain's Index of {pow2_jains:.4f}, which is "
            f"{improvement:.1f}% higher than Random ({random_jains:.4f})."
        )
    else:
        result = "**NOT CONFIRMED** ✗"
        details = (
            f"Pow2 ({pow2_jains:.4f}) did not show better fairness than "
            f"Random ({random_jains:.4f})."
        )

    return f"**Result:** {result}\n\n{details}"


def validate_hypothesis_3(df: pd.DataFrame) -> str:
    """Validate Hypothesis 3: RoundRobin has best fairness."""
    rr_jains = df[df["algorithm"] == "round_robin"]["child_jains"].mean()
    pow2_jains = df[df["algorithm"] == "pow2"]["child_jains"].mean()
    random_jains = df[df["algorithm"] == "random"]["child_jains"].mean()

    is_best = rr_jains > pow2_jains and rr_jains > random_jains
    is_near_perfect = rr_jains > 0.99

    if is_best and is_near_perfect:
        result = "**CONFIRMED** ✓"
        details = (
            f"Round-Robin achieved near-perfect fairness with Jain's Index of {rr_jains:.4f}, "
            f"outperforming Pow2 ({pow2_jains:.4f}) and Random ({random_jains:.4f})."
        )
    elif is_best:
        result = "**PARTIALLY CONFIRMED**"
        details = (
            f"Round-Robin had the best fairness ({rr_jains:.4f}) but not near-perfect. "
            f"Pow2: {pow2_jains:.4f}, Random: {random_jains:.4f}."
        )
    else:
        result = "**NOT CONFIRMED** ✗"
        details = (
            f"Round-Robin ({rr_jains:.4f}) did not have the best fairness. "
            f"Pow2: {pow2_jains:.4f}, Random: {random_jains:.4f}."
        )

    return f"**Result:** {result}\n\n{details}"


def generate_executive_summary(df: pd.DataFrame) -> str:
    """Generate executive summary."""
    best_latency_alg = df.groupby("algorithm")["latency_p99"].mean().idxmin()
    best_fairness_alg = df.groupby("algorithm")["child_jains"].mean().idxmax()
    lowest_error_alg = df.groupby("algorithm")["error_rate"].mean().idxmin()

    return (
        f"This study evaluated three routing algorithms (Power-of-Two Choices, Random, Round-Robin) "
        f"across {len(df['scale'].unique())} scales and {len(df)} total experiment runs.\n\n"
        f"**Key Results:**\n"
        f"- **Best p99 latency:** {best_latency_alg.replace('_', ' ').title()}\n"
        f"- **Best fairness:** {best_fairness_alg.replace('_', ' ').title()}\n"
        f"- **Lowest error rate:** {lowest_error_alg.replace('_', ' ').title()}"
    )


def generate_latency_findings(df: pd.DataFrame) -> str:
    """Generate latency findings section."""
    findings = []
    has_client_parent = "client_parent_delay_mean" in df.columns

    has_parent_child = "parent_child_delay_mean" in df.columns

    for alg in df["algorithm"].unique():
        alg_df = df[df["algorithm"] == alg]
        parent_child_delay = alg_df["parent_child_delay_mean"].mean() if has_parent_child else 0
        
        if has_client_parent:
            client_parent_delay = alg_df["client_parent_delay_mean"].mean()
            findings.append(
                f"- **{alg.replace('_', ' ').title()}:** p50={alg_df['latency_p50'].mean():.1f}ms, "
                f"p99={alg_df['latency_p99'].mean():.1f}ms, "
                f"client→parent={client_parent_delay:.2f}ms, parent→child={parent_child_delay:.2f}ms"
            )
        else:
            findings.append(
                f"- **{alg.replace('_', ' ').title()}:** p50={alg_df['latency_p50'].mean():.1f}ms, "
                f"p99={alg_df['latency_p99'].mean():.1f}ms, parent→child={parent_child_delay:.2f}ms"
            )

    return "\n".join(findings)


def generate_fairness_findings(df: pd.DataFrame) -> str:
    """Generate fairness findings section."""
    findings = []

    for alg in df["algorithm"].unique():
        alg_df = df[df["algorithm"] == alg]
        jains = alg_df["child_jains"].mean()
        cv = alg_df["child_cv"].mean()

        fairness_desc = "excellent" if jains > 0.99 else "good" if jains > 0.95 else "moderate"
        findings.append(
            f"- **{alg.replace('_', ' ').title()}:** Jain's Index={jains:.4f} ({fairness_desc}), CV={cv:.4f}"
        )

    return "\n".join(findings)


def generate_throughput_findings(df: pd.DataFrame) -> str:
    """Generate throughput findings section."""
    findings = []

    for alg in df["algorithm"].unique():
        alg_df = df[df["algorithm"] == alg]
        findings.append(
            f"- **{alg.replace('_', ' ').title()}:** Mean goodput={alg_df['goodput'].mean():.0f} req/s, "
            f"Error rate={alg_df['error_rate'].mean():.2%}"
        )

    return "\n".join(findings)


def generate_utilization_findings(df: pd.DataFrame) -> str:
    """Generate utilization findings section."""
    if "child_util_mean" not in df.columns:
        return "*Utilization data not available.*"
    
    findings = []

    for alg in df["algorithm"].unique():
        alg_df = df[df["algorithm"] == alg]
        mean_util = alg_df["child_util_mean"].mean()
        min_util = alg_df["child_util_min"].mean()
        
        # Interpret utilization
        if mean_util > 0.8:
            efficiency = "highly efficient"
        elif mean_util > 0.5:
            efficiency = "moderately efficient"
        else:
            efficiency = "underutilized (possible router bottleneck)"
        
        findings.append(
            f"- **{alg.replace('_', ' ').title()}:** Mean utilization={mean_util:.1%} ({efficiency}), "
            f"Min={min_util:.1%}"
        )
    
    # Add interpretation note
    findings.append("\n*Note: Low utilization with high routing delay indicates router-side bottlenecks.*")

    return "\n".join(findings)


def generate_recommendations(df: pd.DataFrame) -> str:
    """Generate recommendations section."""
    best_latency = df.groupby("algorithm")["latency_p99"].mean().idxmin()
    best_fairness = df.groupby("algorithm")["child_jains"].mean().idxmax()

    recs = [
        f"1. **For latency-sensitive workloads:** Use {best_latency.replace('_', ' ').title()} "
        f"for optimal tail latency.",
        f"2. **For fairness-critical workloads:** Use {best_fairness.replace('_', ' ').title()} "
        f"for most even request distribution.",
    ]

    # Check if Pow2 is better than random
    pow2_p99 = df[df["algorithm"] == "pow2"]["latency_p99"].mean()
    random_p99 = df[df["algorithm"] == "random"]["latency_p99"].mean()

    if pow2_p99 < random_p99:
        improvement = ((random_p99 - pow2_p99) / random_p99) * 100
        recs.append(
            f"3. **Default recommendation:** The default Pow2 algorithm provides "
            f"{improvement:.0f}% better tail latency than Random routing."
        )

    return "\n".join(recs)


def generate_scale_impact(df: pd.DataFrame) -> str:
    """Generate scale impact analysis."""
    scale_stats = df.groupby("scale").agg({
        "latency_p99": "mean",
        "child_jains": "mean",
        "error_rate": "mean",
    }).round(3)

    lines = ["| Scale | p99 Latency (ms) | Jain's Index | Error Rate |"]
    lines.append("|-------|------------------|--------------|------------|")

    for scale in scale_stats.index:
        row = scale_stats.loc[scale]
        lines.append(
            f"| {scale.title()} | {row['latency_p99']:.1f} | "
            f"{row['child_jains']:.4f} | {row['error_rate']:.2%} |"
        )

    return "\n".join(lines)


def generate_topology_impact(df: pd.DataFrame) -> str:
    """Generate topology impact analysis for Large scale."""
    large_df = df[df["scale"] == "large"]

    if len(large_df) == 0:
        return "*No Large scale data available.*"

    topo_stats = large_df.groupby("topology").agg({
        "latency_p99": "mean",
        "child_jains": "mean",
    }).round(3)

    lines = ["| Topology | p99 Latency (ms) | Jain's Index |"]
    lines.append("|----------|------------------|--------------|")

    for topo in topo_stats.index:
        row = topo_stats.loc[topo]
        lines.append(f"| {topo.title()} | {row['latency_p99']:.1f} | {row['child_jains']:.4f} |")

    return "\n".join(lines)


def generate_locality_impact(df: pd.DataFrame) -> str:
    """Generate locality impact analysis for Large scale."""
    large_df = df[df["scale"] == "large"]

    if len(large_df) == 0:
        return "*No Large scale data available.*"

    loc_stats = large_df.groupby("locality").agg({
        "latency_p99": "mean",
        "child_jains": "mean",
    }).round(3)

    lines = ["| Locality | p99 Latency (ms) | Jain's Index |"]
    lines.append("|----------|------------------|--------------|")

    for loc in loc_stats.index:
        row = loc_stats.loc[loc]
        loc_label = "Preferred" if loc else "None"
        lines.append(f"| {loc_label} | {row['latency_p99']:.1f} | {row['child_jains']:.4f} |")

    return "\n".join(lines)


def generate_algorithm_tables(df: pd.DataFrame) -> str:
    """Generate detailed tables per algorithm."""
    sections = []

    # Build list of metrics to include
    metrics = [
        ("latency_p99", "p99 Latency (ms)"),
        ("child_jains", "Child Jain's Index"),
        ("goodput", "Goodput (req/s)"),
        ("error_rate", "Error Rate"),
    ]
    
    # Add optional metrics if available
    if "client_parent_delay_mean" in df.columns:
        metrics.append(("client_parent_delay_mean", "Client→Parent (ms)"))
    if "parent_child_delay_mean" in df.columns:
        metrics.append(("parent_child_delay_mean", "Parent→Child (ms)"))
    if "child_util_mean" in df.columns:
        metrics.append(("child_util_mean", "Child Utilization"))

    for alg in df["algorithm"].unique():
        alg_df = df[df["algorithm"] == alg]
        alg_name = alg.replace("_", " ").title()

        section = f"### {alg_name}\n\n"
        section += f"**Runs:** {len(alg_df)}\n\n"

        # Summary stats
        section += "| Metric | Mean | Std | Min | Max |\n"
        section += "|--------|------|-----|-----|-----|\n"

        for col, label in metrics:
            if col not in alg_df.columns:
                continue
                
            mean = alg_df[col].mean()
            std = alg_df[col].std()
            min_val = alg_df[col].min()
            max_val = alg_df[col].max()

            if col == "error_rate":
                section += f"| {label} | {mean:.2%} | {std:.2%} | {min_val:.2%} | {max_val:.2%} |\n"
            elif col == "child_jains":
                section += f"| {label} | {mean:.4f} | {std:.4f} | {min_val:.4f} | {max_val:.4f} |\n"
            elif col == "child_util_mean":
                section += f"| {label} | {mean:.2%} | {std:.2%} | {min_val:.2%} | {max_val:.2%} |\n"
            else:
                section += f"| {label} | {mean:.1f} | {std:.1f} | {min_val:.1f} | {max_val:.1f} |\n"

        sections.append(section)

    return "\n".join(sections)


def generate_report(
    df: pd.DataFrame,
    output_path: Optional[Path] = None,
    figures_dir: str = "figures",
) -> str:
    """
    Generate full markdown report with embedded figures.

    Args:
        df: Summary DataFrame.
        output_path: Path to save report (optional).
        figures_dir: Relative path to figures directory from the report location.

    Returns:
        Report as markdown string.
    """
    report = REPORT_TEMPLATE.format(
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        total_runs=len(df),
        unique_configs=len(df.groupby(["algorithm", "scale", "ratio", "topology", "locality", "load_level"])),
        figures_dir=figures_dir,
        executive_summary=generate_executive_summary(df),
        latency_findings=generate_latency_findings(df),
        fairness_findings=generate_fairness_findings(df),
        throughput_findings=generate_throughput_findings(df),
        utilization_findings=generate_utilization_findings(df),
        hypothesis_1=validate_hypothesis_1(df),
        hypothesis_2=validate_hypothesis_2(df),
        hypothesis_3=validate_hypothesis_3(df),
        algorithm_tables=generate_algorithm_tables(df),
        scale_impact=generate_scale_impact(df),
        topology_impact=generate_topology_impact(df),
        locality_impact=generate_locality_impact(df),
        recommendations=generate_recommendations(df),
        latency_table=format_latency_table(df),
        client_to_parent_table=format_client_to_parent_table(df),
        parent_to_child_table=format_parent_to_child_table(df),
        simulated_latency_table=format_simulated_latency_table(df),
        fairness_table=format_fairness_table(df),
        utilization_table=format_utilization_table(df),
    )

    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            f.write(report)
        print(f"Saved report to {output_path}")

    return report


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate summary report from aggregated metrics",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate report with figures in same directory
  python -m analysis.report --input /tmp/routing_results/summary.csv

  # Specify custom output and figures directory
  python -m analysis.report --input /tmp/routing_results/summary.csv \\
      --output /tmp/routing_results/RESULTS.md --figures-dir figures
""",
    )
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Input CSV file with aggregated metrics (e.g., summary.csv from aggregate.py)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIR / "RESULTS.md",
        help=f"Output markdown file. Default: {DEFAULT_OUTPUT_DIR / 'RESULTS.md'}",
    )
    parser.add_argument(
        "--figures-dir",
        type=str,
        default="figures",
        help="Relative path to figures directory from the report location. Default: figures",
    )

    args = parser.parse_args()

    if not args.input.exists():
        print(f"ERROR: Input file not found: {args.input}")
        print("Run analysis/aggregate.py first to generate metrics.")
        exit(1)

    df = pd.read_csv(args.input)
    print(f"Loaded {len(df)} rows from {args.input}")

    report = generate_report(df, args.output, figures_dir=args.figures_dir)
    print("\n" + "=" * 60)

